- docs/sphinx_doc/source/tutorial/example_data_functionalities.md
- docs/sphinx_doc/source/tutorial/example_reasoning_advanced.md
- trinity/cli/launcher.py
Try to activate the data module in the launcher before exploring if one of `dj_config_path` or `dj_process_desc` is set.
> Try to activate data module in the launcher

- README.md
- docs/sphinx_doc/source/main.md
- pyproject.toml
- scripts/docker/Dockerfile
- trinity/common/verl_config.py
> Install from Dockerfile

- trinity/common/workflows/envs/sciworld/sciworld_workflow.py
> add missing workflow

- .github/workflows/docker/docker-compose.yaml
- .github/workflows/unittest.yaml
- pyproject.toml
Update action version and permissions
> Fix unittest action

- .github/workflows/unittest.yaml
- trinity/buffer/reader/sql_reader.py
- trinity/common/verl_config.py
> [HOT FIX] Fix micro_batch_size

- trinity/cli/launcher.py
- trinity/explorer/explorer.py
- trinity/trainer/trainer.py
- trinity/utils/monitor.py
A trick to update wandb after each step
> A trick to update wandb after each step

- pyproject.toml
- trinity/common/config.py
- trinity/common/constants.py
- trinity/trainer/trainer.py
- trinity/trainer/verl_trainer.py
- trinity/utils/monitor.py
Support to monitor the training procedure with tensorboard.
> Add tensorboard monitor

- README.md
- docs/sphinx_doc/source/main.md
- docs/sphinx_doc/source/tutorial/example_dpo.md
- docs/sphinx_doc/source/tutorial/example_reasoning_basic.md
- pyproject.toml
- trinity/buffer/reader/file_reader.py
- trinity/cli/launcher.py
- trinity/common/config.py
- trinity/explorer/explorer.py
- trinity/trainer/trainer.py
- trinity/trainer/verl_trainer.py
- trinity/utils/monitor.py
> Simplify wandb log and update default trainer config

- trinity/cli/launcher.py
- trinity/common/models/vllm_worker.py
- trinity/trainer/verl/fsdp_workers.py
- trinity/utils/distributed.py
- trinity/utils/monitor.py
when using ipv6 master address, the torch.distributed.distributed_c10d.rendezvous can not parse `init_method` correctly, since it use urllib which expected ipv6:port to be `[ipv6]:port`
> fix: init_process_group failed when using ipv6 master address

- examples/grpo_gsm8k/gsm8k.yaml
- trinity/common/config.py
- trinity/common/task.py
Some hf dataset, such as [openai/gsm8k](https://huggingface.co/datasets/openai/gsm8k) has multi config (e.g., "main" and "socratic"), directly load dataset will lead to error. Instead, we should use the user specified `config_name` if provided, and if not, we simply try to load_dataset with dataset name.
This PR also update `examples/grpo_gsm8k/gsm8k.yaml`'s `buffer.train_dataset.path` from `sqlite:////gsm8k.db` to `sqlite:///gsm8k.db`, since `sqlite:////gsm8k.db` will create the db file under the root directory (some may have no permission under a server's root directory), instead `sqlite:///gsm8k.db` will create the db file under the current direcotry.
> fix: some hf dataset may need specified config name

- .gitignore
- docs/sphinx_doc/source/tutorial/example_data_functionalities.md
- docs/sphinx_doc/source/tutorial/example_multi_turn.md
- examples/grpo_gsm8k/gsm8k.yaml
- pyproject.toml
- trinity/buffer/reader/sql_reader.py
- trinity/common/config.py
- trinity/common/verl_config.py
- trinity/explorer/explorer.py
- trinity/trainer/trainer.py
- trinity/utils/monitor.py
> Make 'get_exp_strategy' effective in sql

- README.md
- trinity/cli/launcher.py
- trinity/manager/config_manager.py
1. add CLI for trinity studio
2. add `save` and `run` buttons in the config manager
3. optimize  the structure of the config manager
4. update readme
> Add CLI for Trinity Studio

- tests/common/vllm_test.py
- trinity/common/models/vllm_async_model.py
> Fix `n` does not take effect in vLLM v1 engine

- trinity/common/config.py
- trinity/common/models/vllm_async_model.py
- trinity/common/models/vllm_model.py
- trinity/explorer/runner_pool.py
1. Add a switch for Qwen3 think mode
2. Optimize the initialization of RunnerPool
> Add a switch for Qwen3 think mode

- docs/sphinx_doc/source/tutorial/trinity_configs.md
- pyproject.toml
- tests/explorer/explorer_test.py
- tests/tools.py
- tests/trainer/trainer_test.py
- trinity/cli/launcher.py
- trinity/common/config.py
- trinity/explorer/explorer.py
- trinity/trainer/trainer.py
- trinity/utils/monitor.py
1. Add benchmark() for bench mode
2. Add eval_on_latest_ckp to GlobalConfig
3. Add shutdown for explorer and trainer
> Add benchmark mode

- docs/sphinx_doc/source/tutorial/example_dpo.md
- docs/sphinx_doc/source/tutorial/trinity_configs.md
- examples/async_gsm8k/explorer.yaml
- examples/async_gsm8k/trainer.yaml
- examples/dpo_humanlike/dpo.yaml
- examples/grpo_alfworld/alfworld.yaml
- examples/grpo_gsm8k/gsm8k.yaml
- examples/grpo_math/math.yaml
- examples/grpo_sciworld/sciworld.yaml
- examples/grpo_webshop/webshop.yaml
- examples/opmd_gsm8k/opmd_gsm8k.yaml
- examples/ppo_countdown/countdown.yaml
- trinity/cli/launcher.py
- trinity/common/config.py
- trinity/common/verl_config.py
- trinity/manager/config_manager.py
> Move `algorithm_type` from `trainer` to `global_config`

- docs/sphinx_doc/source/tutorial/example_async_mode.md
- docs/sphinx_doc/source/tutorial/example_dpo.md
- docs/sphinx_doc/source/tutorial/example_multi_turn.md
- docs/sphinx_doc/source/tutorial/example_reasoning_advanced.md
- docs/sphinx_doc/source/tutorial/example_reasoning_basic.md
- examples/async_gsm8k/explorer.yaml
- examples/async_gsm8k/trainer.yaml
- examples/dpo_humanlike/dpo.yaml
- examples/grpo_gsm8k/gsm8k.yaml
- examples/grpo_math/math.yaml
> Update grpo and dpo examples

- docs/sphinx_doc/source/tutorial/trinity_configs.md
- examples/async_gsm8k/verl_config.yaml
- examples/dpo_humanlike/train_dpo.yaml
- examples/grpo_alfworld/train_alfworld.yaml
- examples/grpo_gsm8k/train_gsm8k.yaml
- examples/grpo_math/train_math.yaml
- examples/grpo_sciworld/train_sciworld.yaml
- examples/grpo_webshop/train_webshop.yaml
- examples/opmd_gsm8k/train_opmd_gsm8k.yaml
- examples/ppo_countdown/train_countdown.yaml
- tests/common/config_test.py
- tests/common/vllm_test.py
- tests/template/verl_config.yaml
- trinity/common/config.py
- trinity/common/verl_config.py
- trinity/common/workflows/workflow.py
- trinity/manager/config_manager.py
- trinity/trainer/verl_trainer.py
> Fix config manager

- tests/explorer/runner_pool_test.py
- trinity/common/models/__init__.py
- trinity/explorer/explorer.py
- trinity/explorer/runner_pool.py
> Bug fix in auxiliary_models.

- docs/sphinx_doc/source/tutorial/trinity_programming_guide.md
- trinity/manager/config_manager.py
- trinity/manager/config_registry/__init__.py
- trinity/manager/config_registry/buffer_config_manager.py
- trinity/manager/config_registry/config_registry.py
- trinity/manager/config_registry/explorer_config_manager.py
- trinity/manager/config_registry/model_config_manager.py
- trinity/manager/config_registry/trainer_config_manager.py
> Decompose `config_manager`.

- tests/buffer/sql_test.py
- trinity/buffer/db_wrapper.py
- trinity/buffer/queue.py
- trinity/buffer/reader/queue_reader.py
- trinity/buffer/reader/sql_reader.py
- trinity/buffer/writer/sql_writer.py
- trinity/common/config.py
Add `wrap_in_ray` to `StorageConfig`
When `wrap_in_ray` is set to `True`, the database is wrapped in a Ray actor and provides read and write services for the cluster.
> Wrap database in ray actor

- docs/sphinx_doc/source/tutorial/trinity_programming_guide.md
- tests/utils/plugin_test.py
- tests/utils/plugins/my_workflow.py
- trinity/buffer/buffer.py
- trinity/buffer/reader/file_reader.py
- trinity/cli/launcher.py
- trinity/common/models/__init__.py
- trinity/plugins/__init__.py
- trinity/utils/dlc_utils.py
- trinity/utils/plugin_loader.py
- trinity/utils/registry.py
Automatically load all custom plugin modules in `--plugin-dir`
> Support loading user-written plugin modules automatically

- docs/sphinx_doc/source/tutorial/example_dpo.md
> Add doc for SFT

- tests/buffer/file_test.py
- tests/buffer/queue_test.py
- tests/explorer/runner_pool_test.py
- trinity/buffer/buffer.py
- trinity/buffer/queue.py
- trinity/buffer/ray_wrapper.py
- trinity/buffer/reader/sql_reader.py
- trinity/buffer/utils.py
- trinity/buffer/writer/file_writer.py
- trinity/buffer/writer/sql_writer.py
- trinity/common/config.py
1. Wrap file writer in ray
2. The file/sql path is automatically chosen based on `checkpoint_root_dir`
> Wrap file writer in ray

- trinity/common/models/vllm_async_model.py
- trinity/common/models/vllm_model.py
- trinity/explorer/explorer.py
> Refactor `state_dict_meta` init

- tests/explorer/workflow_test.py
- trinity/common/rewards/reward_fn.py
- trinity/common/workflows/__init__.py
- trinity/common/workflows/customized_math_workflows.py
- trinity/utils/eval_utils.py
As the title says. The customized math workflow use the `workflow_args` field.
> Customized math workflows

- tests/trainer/trainer_test.py
- trinity/cli/launcher.py
- trinity/common/constants.py
- trinity/common/models/vllm_worker.py
- trinity/explorer/explorer.py
- trinity/trainer/trainer.py
- trinity/trainer/verl/fsdp_workers.py
- trinity/trainer/verl_trainer.py
> Support one-step ahead async RL

- trinity/cli/launcher.py
- trinity/common/config.py
- trinity/common/models/vllm_async_model.py
- trinity/common/models/vllm_model.py
- trinity/common/models/vllm_worker.py
> Bug Fix in `namespace`

- docs/sphinx_doc/source/tutorial/trinity_configs.md
- tests/trainer/trainer_test.py
- trinity/cli/launcher.py
- trinity/common/config.py
> Add ray timeline for profiling

- tests/trainer/trainer_test.py
- trinity/explorer/explorer.py
> Refactor explorer loop

- trinity/common/verl_config.py
- trinity/common/workflows/envs/alfworld/alfworld_workflow.py
- trinity/explorer/explorer.py
- trinity/manager/config_manager.py
- trinity/manager/config_registry/trainer_config_manager.py
- trinity/trainer/trainer.py
- trinity/trainer/verl_trainer.py
- trinity/utils/monitor.py
> Bug Fix && Add more logger info

- docs/sphinx_doc/source/tutorial/trinity_configs.md
- trinity/common/config.py
- trinity/explorer/runner_pool.py
- trinity/trainer/trainer.py
> Bug fix in alfworld

- README.md
- docs/sphinx_doc/source/index.rst
- docs/sphinx_doc/source/tutorial/example_mix_algo.md
- docs/sphinx_doc/source/tutorial/faq.md
- docs/sphinx_doc/source/tutorial/trinity_configs.md
- examples/async_gsm8k/verl_config.yaml
- examples/dpo_humanlike/train_dpo.yaml
- examples/grpo_alfworld/alfworld.yaml
- examples/grpo_alfworld/train_alfworld.yaml
- examples/grpo_gsm8k/train_gsm8k.yaml
- examples/grpo_gsm8k_experience_pipeline/train_gsm8k.yaml
- examples/grpo_gsm8k_task_pipeline/train_gsm8k.yaml
- examples/grpo_math/README.md
- examples/grpo_math/train_math.yaml
- examples/grpo_sciworld/train_sciworld.yaml
- examples/grpo_webshop/train_webshop.yaml
- examples/mix_math/train_mix_math.yaml
- examples/opmd_gsm8k/train_opmd_gsm8k.yaml
- examples/ppo_countdown/README.md
- examples/ppo_countdown/train_countdown.yaml
> Add FAQ in docs

- docs/sphinx_doc/source/tutorial/example_mix_algo.md
- tests/buffer/queue_test.py
- tests/explorer/scheduler_test.py
- trinity/algorithm/sample_strategy/mix_sample_strategy.py
- trinity/algorithm/sample_strategy/utils.py
- trinity/buffer/reader/queue_reader.py
- trinity/common/config.py
- trinity/common/experience.py
- trinity/common/workflows/workflow.py
- trinity/explorer/scheduler.py
- trinity/explorer/workflow_runner.py
Add `explorer.max_repeat_times`, which limits the number of times a single runner can repeat a task, thereby splitting tasks with larger `repeat_times` into multiple subtasks to be executed on different runners. When `explorer.max_repeat_times` is not set, no splitting will be performed.
This method can reduce the overall latency of tasks with large `repeat_times` and lower the cost of failed retries; however, it will also cause the rollout results of the same group to be scattered. Users must decide whether to enable this function based on their actual needs.
> Split group of tasks to multiple runners

- .github/workflows/unittest.yaml
- `/unittest-all`: Run all unit-tests
- `/unittest-diff`: Check for changed modules and run tests in those modules
- `/unittest-module-xxx`: Run tests in xxx module
> Add more unittest command

- examples/grpo_math/README.md
- trinity/common/rewards/reward_fn.py
> Fix MATH readme

- trinity/algorithm/add_strategy/__init__.py
- trinity/common/workflows/customized_math_workflows.py
- trinity/common/workflows/customized_toolcall_workflows.py
- trinity/common/workflows/math_rm_workflow.py
- trinity/common/workflows/workflow.py
> Add run_id for single-turn workflows

- tests/explorer/scheduler_test.py
- trinity/algorithm/add_strategy/add_strategy.py
- trinity/algorithm/advantage_fn/grpo_advantage.py
- trinity/algorithm/advantage_fn/opmd_advantage.py
- trinity/algorithm/advantage_fn/rloo_advantage.py
- trinity/common/workflows/workflow.py
- trinity/explorer/scheduler.py
- []  Code has passed all tests
> Bug fix for `Scheduler` and `torch.tensor`

- trinity/buffer/reader/file_reader.py
As the title says. To avoid revising meta.args when splitting tasks.
> Fix a bug in args_pass

- tests/common/vllm_test.py
- trinity/common/config.py
- trinity/common/models/api/vllm_patch.py
- trinity/common/models/vllm_model.py
- trinity/manager/config_manager.py
- trinity/manager/config_registry/explorer_config_manager.py
As the title says. We use an OpenAI-compatible format for our tool calls. 
> Add tool call usage from our vllm model

- tests/common/synchronizer_test.py
- trinity/algorithm/sample_strategy/mix_sample_strategy.py
- trinity/algorithm/sample_strategy/sample_strategy.py
- trinity/buffer/buffer_reader.py
- trinity/buffer/reader/file_reader.py
- trinity/buffer/reader/queue_reader.py
- trinity/buffer/reader/sql_reader.py
- trinity/common/synchronizer.py
- trinity/data/core/dataset.py
- trinity/explorer/explorer.py
- trinity/trainer/trainer.py
- trinity/trainer/verl/fsdp_workers.py
- trinity/trainer/verl_trainer.py
1. Refactor `Trainer.train` to async function.
2. Modify lifetime for synchronizer for bug fix
> Refactor `Trainer.train` to async function

- tests/common/synchronizer_test.py
- trinity/common/synchronizer.py
- trinity/explorer/explorer.py
- trinity/trainer/trainer.py
> Add auto release for `synchronizer`

- tests/explorer/step_wise_workflow_test.py
> Add step-wise workflow test

- .github/workflows/docker/docker-compose.yaml
- .github/workflows/unittest.yaml
- docs/sphinx_doc/source/tutorial/example_async_mode.md
- docs/sphinx_doc/source/tutorial/example_dpo.md
- docs/sphinx_doc/source/tutorial/example_mix_algo.md
- docs/sphinx_doc/source/tutorial/faq.md
- docs/sphinx_doc/source/tutorial/trinity_configs.md
- examples/async_gsm8k/trainer.yaml
- examples/dpo_humanlike/dpo.yaml
- examples/mix_math/mix_math.yaml
- examples/sft_mot/sft.yaml
- tests/buffer/queue_test.py
- tests/buffer/sql_test.py
- tests/common/vllm_test.py
- tests/explorer/scheduler_test.py
- tests/manager/synchronizer_test.py
- tests/template/config.yaml
- tests/template/verl_config.yaml
- tests/trainer/trainer_test.py
- trinity/algorithm/policy_loss_fn/mix_policy_loss.py
- trinity/algorithm/sample_strategy/mix_sample_strategy.py
- trinity/buffer/queue.py
- trinity/buffer/ray_wrapper.py
- trinity/buffer/reader/file_reader.py
- trinity/buffer/reader/queue_reader.py
- trinity/common/config.py
- trinity/common/verl_config.py
- trinity/manager/config_manager.py
- trinity/manager/config_registry/buffer_config_manager.py
- trinity/trainer/verl/fsdp_workers.py
Also fix some bugs in config manager.
> [Feat] Allow user to set `train_batch_size`

- trinity/common/models/vllm_model.py
Partially fixing:
- https://github.com/modelscope/Trinity-RFT/issues/197
---
To prevent vllm throwing exceptions like:
`ERROR 08-17 23:32:15 scheduler.py:86] ValueError: The decoder prompt (length 42861) is longer than the maximum model length of 32768. Make sure that max_model_len is no smaller than the number of text tokens.`
`truncate_prompt_tokens=config.max_model_len-1` is used to ensure at least one output token
A similar setting was used before https://github.com/modelscope/Trinity-RFT/pull/172, and got removed without an explanation that I could find
> Set truncate_prompt_tokens in SamplingParams, silently truncating very large prompts and preventing vllm from throwing exception

- trinity/common/config.py
- trinity/trainer/verl_trainer.py
**Background:** 
When using models like Llama where the default `pad_token_id` is `None`, the sampler_strategy could be incorrect if `pad_token_id` wasn't explicitly set in the config. Both Verl and vLLM automatically handle this during tokenizer loading by setting appropriate `pad_token_id` values.
**Purpose:** 
Update the config after tokenizer loading to ensure the `pad_token_id` is properly set, making the sampler_strategy consistent and correct.
**Changes made:**
- Added config update logic after tokenizer loading to set `pad_token_id` when it's `None` in the original config
- Ensures sampler_strategy uses the correct `pad_token_id` that Verl/vLLM have automatically determined during tokenizer initialization
- Maintains alignment between our config and the actual tokenizer …
> Auto-set pad_token_id when the default is None and not set in the buffer config.

- tests/common/vllm_test.py
- trinity/common/config.py
- trinity/common/constants.py
- trinity/common/models/vllm_model.py
> Add `max_prompt_tokens`

- README.md
- README_zh.md
- docs/sphinx_doc/source/main.md
- trinity/trainer/verl/dp_actor.py
- trinity/utils/plugin_loader.py
> Release v0.2.1

- README.md
- README_zh.md
- docs/sphinx_doc/source/main.md
- pyproject.toml
- trinity/cli/launcher.py
> Bumping version to 0.2.1

- docs/sphinx_doc/source/tutorial/example_dpo.md
- docs/sphinx_doc/source/tutorial/example_reasoning_basic.md
- docs/sphinx_doc/source/tutorial/trinity_configs.md
- examples/dpo_humanlike/dpo.yaml
- tests/buffer/formatter_test.py
- tests/cli/launcher_test.py
- trinity/buffer/buffer_reader.py
- trinity/buffer/ray_wrapper.py
- trinity/buffer/reader/file_reader.py
- trinity/buffer/reader/queue_reader.py
- trinity/buffer/reader/sql_reader.py
- trinity/buffer/schema/formatter.py
- trinity/cli/launcher.py
- trinity/common/config.py
- trinity/common/constants.py
1. Add `Formatter` to format SFT/DPO data.
2. Remove `CHATPAIR` PromptType
3. Remove `ReadStrategy` from buffer reader
4. Remove some unused fields in `FormatConfig`
> Enhance SFT/DPO reader

- tests/trainer/trainer_test.py
- trinity/trainer/verl/fsdp_workers.py
> Bug fix for FSDP offload

- trinity/utils/monitor.py
> Add `log_table` function for mlflow

- trinity/service/data_juicer/server/session.py
- trinity/service/data_juicer/server/utils.py
Support 4 task ordering methods:
- keep: keep the original order.
- shuffle: randomly shuffle the task order.
- sort: sort the tasks according to their priority score.
- folding: folding the tasks into L layers after they are sorted. Ref: https://arxiv.org/abs/2506.21545
> Support new task ordering methods

- .github/workflows/docker/docker-compose.yaml
- benchmark/config/countdown-template.yaml
- benchmark/config/gsm8k-template.yaml
- docs/sphinx_doc/source/tutorial/trinity_configs.md
- docs/sphinx_doc/source_zh/tutorial/trinity_configs.md
- pyproject.toml
- scripts/docker/Dockerfile
- scripts/docker_for_megatron/Dockerfile
- tests/common/vllm_test.py
- tests/template/verl_config.yaml
- trinity/buffer/storage/file.py
- trinity/buffer/storage/queue.py
- trinity/common/config.py
- trinity/common/models/model.py
- trinity/manager/config_manager.py
1. Remove `val_before_train` in config.
2. Remove empty path in experience_buffer.
3. Improved the situation where the `storage_config.path` is empty.
4. Update rm-gallery to 0.1.5. #253
5. Rename `model_type` to `engine_type` and remove `vllm_async`
6. Add `max_tokens` to `GenerationConfig`.
7. Refactor config check.
> Improvement in config

- examples/grpo_gsm8k/gsm8k.yaml
- examples/mix_chord/mix_chord.yaml
- examples/mix_math/mix_math.yaml
- tests/cli/launcher_test.py
- tests/common/vllm_test.py
- tests/explorer/explorer_test.py
- tests/explorer/scheduler_test.py
- tests/trainer/trainer_test.py
- trinity/algorithm/sample_strategy/mix_sample_strategy.py
- trinity/buffer/pipelines/experience_pipeline.py
- trinity/buffer/storage/sql.py
- trinity/cli/launcher.py
- trinity/common/config.py
- trinity/common/models/api/vllm_patch.py
- trinity/common/models/model.py
- trinity/common/models/utils.py
- trinity/common/models/vllm_model.py
- trinity/explorer/api/api.py
- trinity/explorer/api/server.py
- trinity/explorer/api/service.py
- trinity/explorer/explorer.py
- trinity/explorer/explorer_client.py
- trinity/explorer/scheduler.py
- trinity/explorer/workflow_runner.py
- trinity/manager/state_manager.py
Propose `serve` mode in this PR.
In `serve` mode
- Only Explorer will be started, and the `buffer.explorer_input` will be ignored. 
- Explorer provides an OpenAI API-compatible inference service.
- Explorer dynamically assigns requests to the inference models within it.
- Explorer automatically converts inference requests and responses into `Experience` data and write them to buffer.
- Explorer keeps tracking the latest checkpoint generated by Trainer (which can be run in another cluster)
- Explorer ensures that there is at least one running (not syncing weights) inference model at any time.
With `serve` mode, agent application developers can deploy their Agent applications locally and use the inference services provided by a remote Explorer.
Please check the following items before code …
> Explorer provides OpenAI API compatible inference service
